# Generated by Django 5.1.2 on 2024-10-12 03:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('responsibilities', ckeditor.fields.RichTextField()),
                ('qualifications', ckeditor.fields.RichTextField()),
                ('benefits', ckeditor.fields.RichTextField()),
                ('employment_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('C', 'Contract')], max_length=2)),
                ('salary_description', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry-Level'), ('Mid', 'Mid-Level'), ('Senior', 'Senior-Level')], default='Entry', max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_profile_url', models.CharField(max_length=2083)),
                ('additional_info', ckeditor.fields.RichTextField()),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='careers.jobtag'),
        ),
    ]
