# Generated by Django 5.1 on 2024-09-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_options_article_preview_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
